language: ruby
rvm:
  - 2.0.0
cache: bundler
sudo: false
notifications:
  flowdock: e02b1335699722cbb4a995c82e2ca7ff
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bin/rake db:schema:load RAILS_ENV=test
script: xvfb-run bin/rspec spec/
